import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_lucide/flutter_lucide.dart';
import '../../../core/theme/liq_colors.dart';
import '../../../core/ui/glass_card.dart';

class DynIsland extends StatefulWidget {
  const DynIsland({super.key});

  @override
  State<DynIsland> createState() => _DynIslandState();
}

class _DynIslandState extends State<DynIsland> {
  bool isExpanded = false;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        setState(() {
          isExpanded = !isExpanded;
        });
      },
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 400),
        curve: Curves.easeOutExpo,
        width: isExpanded ? MediaQuery.of(context).size.width * 0.9 : 140,
        height: isExpanded ? 220 : 40,
        decoration: BoxDecoration(
          color: Colors.black,
          borderRadius: BorderRadius.circular(isExpanded ? 32 : 20),
          border: Border.all(
            color: Colors.white.withOpacity(0.1),
            width: 1,
          ),
        ),
        child: isExpanded ? _buildExpandedPlayer() : _buildCompactPill(),
      ),
    );
  }

  Widget _buildCompactPill() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        const Icon(Icons.waves_rounded, color: LiqColors.accentGreen, size: 16)
            .animate(onPlay: (c) => c.repeat())
            .shimmer(duration: 2.seconds, color: Colors.white),
        const SizedBox(width: 8),
        Text(
          "AI Podcast",
          style: GoogleFonts.inter(
            color: Colors.white,
            fontSize: 14,
            fontWeight: FontWeight.w500,
          ),
        ),
      ],
    ).animate().fadeIn(duration: 200.ms);
  }

  Widget _buildExpandedPlayer() {
    return GlassCard(
      radius: 32,
      blur: 30,
      padding: const EdgeInsets.all(20),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Container(
                width: 60,
                height: 60,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(16),
                  image: const DecorationImage(
                    image: NetworkImage("https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=200&auto=format&fit=crop"),
                    fit: BoxFit.cover,
                  ),
                ),
              ),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 16.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        "Neurology Chapter 4",
                        style: GoogleFonts.poppins(
                          color: Colors.white,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                      Text(
                        "Generated by ILM AI",
                        style: GoogleFonts.inter(
                          color: Colors.white54,
                          fontSize: 14,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Icon(Icons.waves_rounded, color: LiqColors.accentGreen, size: 24)
                  .animate(onPlay: (c) => c.repeat())
                  .shimmer(duration: 1.5.seconds, color: Colors.white),
            ],
          ),
          const Spacer(),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              const Icon(LucideIcons.skip_back, color: Colors.white, size: 28),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.white,
                  shape: BoxShape.circle,
                  boxShadow: [
                    BoxShadow(
                      color: Colors.white.withOpacity(0.3),
                      blurRadius: 12,
                      spreadRadius: 2,
                    )
                  ],
                ),
                child: const Icon(LucideIcons.pause, color: Colors.black, size: 28),
              ),
              const Icon(LucideIcons.skip_forward, color: Colors.white, size: 28),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text("01:24", style: GoogleFonts.inter(color: Colors.white54, fontSize: 12)),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 8.0),
                  child: Container(
                    height: 4,
                    decoration: BoxDecoration(
                      color: Colors.white24,
                      borderRadius: BorderRadius.circular(2),
                    ),
                    alignment: Alignment.centerLeft,
                    child: FractionallySizedBox(
                      widthFactor: 0.4,
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(2),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Text("-03:12", style: GoogleFonts.inter(color: Colors.white54, fontSize: 12)),
            ],
          )
        ],
      ),
    ).animate().fadeIn(duration: 300.ms);
  }
}